### ISSUE TITLE
Idea: create a twitter card image for each app

### ISSUE THREAD

**Issue by zeke** [electron/electron-apps#118]
When we start making standalone app pages, then links in places like Slack could have a nice preview, assuming we get the `meta` tags right and everything:

<img width="819" alt="screen shot 2017-03-02 at 2 04 32 pm" src="https://cloud.githubusercontent.com/assets/2289/23529113/2f364b20-ff51-11e6-9ae6-4c446a690a6d.png">

**Comment by zeke** [comment]
@jkleinsc didn't you end up working on this?

**Comment by jkleinsc** [comment]
Yup. It is done for the new site

**Comment by zeke** [comment]
> new site

https://github.com/electron/electron.atom.io/pull/758
