### ISSUE TITLE
Zeplin is not using electron

### ISSUE THREAD

**Issue by acao** [electron/electron-apps#272]
</3

https://twitter.com/zeplin_io/status/842437674606637060

i thought i'd look into this when i saw the update was only 12MB - i was wondering how they pulled it off with electron! as it turns out, the app is entirely native

**Comment by zeke** [comment]
That's strange. The Zeplin folks were really eager to collaborate on a blog post about their use of Electron not so long ago... 🤔

**Comment by merih** [comment]
We've just found this issue and corresponding pull request! Our macOS app is fully native, but our Windows app is built with Electron. That question in the tweet was about our macOS app, hence the answer. Sorry for the confusion.

We're still eager for the blog post too!

**Comment by acao** [comment]
oh hooray! my mistake

**Comment by Carbonneau** [comment]
@merih If Zeplin for windows is electron, does that mean that there could be a linux build? I Would love that.
