### ISSUE TITLE
Front-End Box link seems to be broken...

### ISSUE THREAD

**Issue by cedric25** [electron/electron-apps#307]
The URL where it redirects to: http://frontendbox.io/
Not sure this is considered as a problem for this repo, but if the issue persists, it might be better to remove the reference.
(Hope it's not a problem with my config. Otherwise sorry for the noise.
(Not sure I should have opened an issue for that...)

**Comment by zeke** [comment]
Fixed by https://github.com/electron/electron-apps/pull/345
