### ISSUE TITLE
app sorting

### ISSUE THREAD

**Issue by gautamsi** [electron/electron-apps#41]
I was following the apps as an when they were added, I see that it is now sorted by name. it is difficult to follow new apps among the sea of apps listed here.

Can this be sorted by the date it is added again? or can there be option to sort it by the date or name with month based grouping?

**Comment by larabih** [comment]
Me too, i'm followong the electron new apps. I  prefer a "sorted by " option ...

**Comment by zeke** [comment]
Good point. We will work on a solution for this. Stay tuned!

**Comment by zeke** [comment]
I did some work to collect app submission dates from the git history. It's all here now: https://github.com/electron/electron-apps/blob/master/meta/dates.json

The build process will continue collecting dates for all apps going forward.

When you install this module with npm, the dates are included in the metadata for each app:

```
$yarn global add trymodule && trymodule electron-apps=apps
```

Then:

```js
apps[0]
```

Which yields:

```js
{ slug: '1clipboard',
  name: '1Clipboard',
  description: 'A universal clipboard managing app that makes it easy to access your clipboard from anywhere on any device',
  website: 'http://1clipboard.io',
  icon: '1clipboard-icon.png',
  icon32: '1clipboard-icon-32.png',
  icon64: '1clipboard-icon-64.png',
  icon128: '1clipboard-icon-128.png',
  date: '2016-03-31',
  iconColors: [ '#14538b', '#eff0f1', '#6b88a7', '#849cb4', '#8c9cb4' ]
}
```

Now that we have the data, the next step will be to surface on the website.

**Comment by zeke** [comment]
Apps are now sorted by date on the website, with newest submissions at the top. This has been fixed for a while, but I forgot to close the issue here.
