### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by zeke** [electron/electron-apps#45]
Just collecting some prior art here, in case we want to introduce a set list of categories.

- https://developer.apple.com/app-store/categories/
- https://support.google.com/googleplay/android-developer/answer/113475?hl=en

![screen shot 2016-12-28 at 7 53 03 pm](https://cloud.githubusercontent.com/assets/2289/21536405/778c67c0-cd37-11e6-9591-61caf08619e2.png)

![screen shot 2016-12-28 at 7 53 23 pm](https://cloud.githubusercontent.com/assets/2289/21536406/7c2278ba-cd37-11e6-8633-91959a041a11.png)

![screen shot 2016-12-28 at 7 52 50 pm](https://cloud.githubusercontent.com/assets/2289/21536403/7474875c-cd37-11e6-831a-df88a44e7357.png)

**Comment by zeke** [comment]
<img width="349" alt="screen shot 2017-01-13 at 12 01 52 pm" src="https://cloud.githubusercontent.com/assets/2289/21943867/10315d8a-d988-11e6-9194-6bc9f11b9561.png">

**Comment by YurySolovyov** [comment]
Are we going to proceed with this? If so, what needs to be done?

**Comment by zeke** [comment]
I've just been using this issue to collect existing categories from related products.

@YurySolovyov if you want to move this forward, that would be great.

> what needs to be done?

1. Create a list of app categories.
1. Update all the apps to fit into a category.
1. Update the website to display a list of category links that filter the app list.

**Comment by zeke** [comment]
Fixed by #225, and there's now a followup issue at https://github.com/electron/electron.atom.io/issues/759
