### ISSUE TITLE
Verify homepage and repository URLs for new apps

### ISSUE THREAD

**Issue by zeke** [electron/electron-apps#88]
When a new app is added, we should check that the URLs are legit.

The test suite could somehow isolate that newly added app (by looking at the latest git commit) and test that its `homepage` and/or `repository` URLs are returning 200 status codes.

This test should NOT be run for every app on every test run. That would be slow and probably cause intermittent test failures.

**Comment by victorhsn** [comment]
@zeke, maybe we could use the node request  to verify if an url is legit as below;

`var request = require('request')`

`request({url: value, method: 'HEAD'}, function(err, res) {`
   `if(err) return false;`
`})`

If the url is legit the request will return the code 200 (res.statusCode).

What do you think about it?

**Comment by zeke** [comment]
Yeah that sounds about right. I think the trickier part may be teaching the tests to only evaluate the most recently added app.

**Comment by victorhsn** [comment]
@zeke yes, because it could lead some time to check the URLs. But I was thinking about it and we could evaluate the most recently apps when the wizard for executed before of show the first question...

**Comment by zeke** [comment]
I'm not sure I understand what you're suggesting about the wizard.

**Comment by zeke** [comment]
This doesn't seem necessary after all. Closing.
